development:
  sessions:
    default:
      database: auth_with_cuba_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: auth_with_cuba_development_test
      hosts:
        - localhost:27017
